name: Build Flutter iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Clean Build Directory
        run: flutter clean

      - name: Build iOS App without Codesign & Provisioning
        run: |
          flutter build ios --release --no-codesign --config-only
          cd ios
          xcodebuild -workspace Runner.xcworkspace -scheme Runner -configuration Release -sdk iphoneos CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

      - name: Create Payload and Package IPA
        run: |
          mkdir -p Payload
          # Megkeressük a lefordított .app fájlt bárhol is legyen
          find build/ios/iphoneos -name "*.app" -exec cp -r {} Payload/ \;
          zip -r Runner.ipa Payload

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: Runner.ipa
